# Generated by Django 4.0 on 2024-02-21 04:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('userFullName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres y Apellidos')),
                ('userIdentification', models.IntegerField(null=True, unique=True, verbose_name='Documento Identificación')),
                ('userProfessionalCard', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tarjeta profesional')),
                ('userPhone', models.IntegerField(null=True, verbose_name='Teléfono')),
                ('userOwner', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('hash', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modificated', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createOrder', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modificated', models.DateTimeField(blank=True, null=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(blank=True, null=True, verbose_name='id de encargo')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('modificated', models.DateTimeField(blank=True, null=True)),
                ('order_name', models.CharField(max_length=255, null=True, unique=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserLicenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LicensesId', models.IntegerField(blank=True, null=True, verbose_name='id de licencia')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modificated', models.DateTimeField(blank=True, null=True)),
                ('orders_quantity', models.IntegerField(null=True)),
                ('users_quantity', models.IntegerField(null=True)),
                ('license_name', models.CharField(max_length=150, null=True, unique=True)),
                ('pesos_col', models.BigIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='Correo Electrónico')),
                ('userFullName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres y Apellidos')),
                ('userIdentification', models.IntegerField(db_index=True, null=True, verbose_name='Documento Identificación')),
                ('userProfessionalCard', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tarjeta profesional')),
                ('userPhone', models.IntegerField(null=True, verbose_name='Teléfono')),
                ('userOwner', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('hash', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('modificated', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_app.user')),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'verbose_name_plural': 'historical Usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FilesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.IntegerField(blank=True, null=True, verbose_name='id de encargo')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('modificated', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255, null=True, unique=True)),
                ('file_url', models.CharField(max_length=255, null=True, unique=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
        ),
    ]
