# Generated by Django 4.0 on 2024-02-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesorder',
            name='LicensesId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.userlicenses'),
        ),
        migrations.AddField(
            model_name='filesorder',
            name='orderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.userorders'),
        ),
        migrations.AddField(
            model_name='userorders',
            name='LicensesId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.userlicenses'),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.IntegerField(blank=True, null=True, verbose_name='id de encargo')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('modificated', models.DateTimeField(blank=True, null=True)),
                ('LicensesId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.userlicenses')),
                ('orderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.userorders')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.user')),
            ],
        ),
    ]
